version: '3'

services:
    symfony:
        build:
            context: ../../
            dockerfile: ./docker/symfony/dockerfile
            args:
                ENV: pre
                APP_FOLDER: ${APP_FOLDER}
        restart: always
        volumes:
            - "../../${APP_FOLDER}/config/jwt/:/var/www/html/config/jwt/"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_symfony.rule=Host(`api-ticketing.pre.ticketing.oaro.work`) && PathRegexp(`/[a-z]{2}/v2/`)"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}_symfony.loadbalancer.server.port=80"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_symfony.entrypoints=https"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_symfony.tls=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_symfony.tls.certresolver=myresolver"
networks:
    default:
        name: traefik
        external: true